# Generated by Django 5.0.4 on 2024-08-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('size', '0002_alter_size_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
