POST http://127.0.0.1:8000/api-auth/login/
Content-type: application/json

{ "username": "admin", "password": "admin" }

###

POST http://127.0.0.1:8000/api-auth/login/
Content-type: application/json

{ "username": "test", "password": "test" }

###

POST http://127.0.0.1:8000/api-auth/signup/
Content-type: application/json

{ "username": "test", "password": "test", "email": "test@test.com" }

###
POST http://127.0.0.1:8000/products/
Content-type: application/json
Authorization: Token 1edee542e2fa92de9fbec589c00548f191655c3e
# Authorization: Token 279d38d84e4a8e0d7d1db5b8322a359896a7b6f4

{
    "name": "this is last test Prodcut",
    "price": "800.00",
    "image": "E:/photoshop/galery/jpg/iamtrust_me_iam_a_doctor.jpg",
    "description": "",
    "created_at": "2024-08-16T20:52:28.456230Z",
    "tags": [
        {
            "id": 3,
            "name": "shorts"
        }
    ]
}

###
PUT http://127.0.0.1:8000/products/10/
Content-type: application/json
Authorization: Token 1edee542e2fa92de9fbec589c00548f191655c3e
# Authorization: Token 279d38d84e4a8e0d7d1db5b8322a359896a7b6f4

{
    "name": "changeTest"
}

###
PUT http://127.0.0.1:8000/orders/4/
Content-type: application/json
# Authorization: Token d6cdaf444065d8568b754246a7f5e7af5f4404f0
Authorization: Token 279d38d84e4a8e0d7d1db5b8322a359896a7b6f4

{
    "product": 6
}

###

GET http://127.0.0.1:8000/orders/
Content-type: application/json
Authorization: Token 1edee542e2fa92de9fbec589c00548f191655c3e
# Authorization: Token 279d38d84e4a8e0d7d1db5b8322a359896a7b6f4

{
}

###
GET http://127.0.0.1:8000/orderItems/2
Content-type: application/json
# Authorization: Token 1edee542e2fa92de9fbec589c00548f191655c3e
Authorization: Token f35049a696377b630739cb42533acdcdc7cd59fb

{
    "product": 11,
    "quantity": 100
}

###
GET http://127.0.0.1:8000/orderItems/cart/
Content-type: application/json
Authorization: Token 1edee542e2fa92de9fbec589c00548f191655c3e
# Authorization: Token 279d38d84e4a8e0d7d1db5b8322a359896a7b6f4

{
    "product": 10
}

###

GET http://127.0.0.1:8000/order/
Content-type: application/json
Authorization: Token d6cdaf444065d8568b754246a7f5e7af5f4404f0
# Authorization: Token 279d38d84e4a8e0d7d1db5b8322a359896a7b6f4

{

}

###
POST http://127.0.0.1:8000/order/
Content-type: application/json
Authorization: Token d6cdaf444065d8568b754246a7f5e7af5f4404f0
# Authorization: Token 279d38d84e4a8e0d7d1db5b8322a359896a7b6f4

{

}

###
PUT http://127.0.0.1:8000/order/24/
Content-type: application/json
Authorization: Token d6cdaf444065d8568b754246a7f5e7af5f4404f0
# Authorization: Token 279d38d84e4a8e0d7d1db5b8322a359896a7b6f4

{
    "user": 4
}

###
DELETE http://127.0.0.1:8000/order/24/
Content-type: application/json
Authorization: Token d6cdaf444065d8568b754246a7f5e7af5f4404f0
# Authorization: Token 279d38d84e4a8e0d7d1db5b8322a359896a7b6f4

{
}

###
