# Generated by Django 5.0.4 on 2024-08-24 06:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='type',
            field=models.CharField(choices=[('add', 'Add'), ('minus', 'Minus')], default='add', max_length=20),
        ),
    ]
