# Generated by Django 5.0.4 on 2024-08-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
