# Generated by Django 5.0.4 on 2024-08-19 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
        ('orderItem', '0003_rename_singularproductorder_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='gathered_orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.gatheredorders'),
        ),
    ]
