# Generated by Django 5.0.4 on 2024-08-20 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderItem', '0004_alter_orderitem_gathered_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='gathered_orders',
            new_name='order',
        ),
    ]
