# Generated by Django 5.0.4 on 2024-08-24 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderItem', '0007_alter_orderitem_order'),
        ('size', '0003_alter_size_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='size.size'),
        ),
    ]
