# Generated by Django 5.0.4 on 2024-08-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('shipping', 'Shipping'), ('delivered', 'Delivered')], default='pending', max_length=255, null=True)),
                ('addressText', models.CharField(max_length=1000)),
                ('city', models.CharField(default='Cairo', max_length=100)),
                ('country', models.CharField(default='Egypt', max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
    ]
