# Generated by Django 5.0.4 on 2024-08-24 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('order', '0003_rename_gatheredorders_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='address.address'),
            preserve_default=False,
        ),
    ]
