# Generated by Django 5.0.4 on 2024-08-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('shipping', 'Shipping'), ('delivered', 'Delivered')], max_length=255, null=True),
        ),
    ]
