# Generated by Django 5.0.4 on 2024-09-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ordre_last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
