# Generated by Django 5.0.4 on 2024-09-06 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_order_first_name_order_ordre_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordre_last_name',
            new_name='order_last_name',
        ),
    ]
